FROM quay.io/redhat-services-prod/openshift/boilerplate:image-v8.3.6 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o mock-api ./cmd/mock-api

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN groupadd -g 1001 rhobs && \
    useradd -u 1001 -g 1001 -m -d /home/rhobs -s /bin/sh rhobs

WORKDIR /home/rhobs
COPY --from=builder /app/mock-api ./

RUN chown -R rhobs:0 /home/rhobs && \
    chmod -R g=u /home/rhobs && \
    chmod +x ./mock-api

EXPOSE 8080
USER rhobs
ENTRYPOINT ["./mock-api"]
